### ISSUE TITLE
3.0.0: Tests not in sdist tarball on pypi.org

### ISSUE THREAD

**Issue by dvzrv** [django-cms/django-classy-tags#69]
Hi! When attempting to package version 3.0.0 I noticed that the sdist tarball on pypi.org still does not contain the tests (see https://github.com/django-cms/django-classy-tags/issues/52#issuecomment-577638993).

Can they please be added to the sdist tarball? :)

**Comment by marksweb** [comment]
Hi @dvzrv! I hope I understand what you're after now.

Looking at the current release, the tarball only contains the python of the tests directory. But you need that to include everything so that you can actually run it.

![Screenshot 2022-01-27 at 19 58 28](https://user-images.githubusercontent.com/1461191/151434938-d6be0ec4-d8de-4a59-937c-60ab86aedfb9.png)

So I've updated the manifest to include the requirements and templates so that the tests should be able to function. Now the tarball includes all this;
![Screenshot 2022-01-27 at 20 01 21](https://user-images.githubusercontent.com/1461191/151435181-38a69b65-70cf-4210-bd02-ece965b07bec.png)

Is that right?

**Comment by dvzrv** [comment]
> Is that right?

Thanks! That looks alright now! :)

**Comment by marksweb** [comment]
@dvzrv Please try 3.0.1 which I've just released. Hopefully that's got what you need now

**Comment by dvzrv** [comment]
Thanks a lot! :)
